-- Insert 35+ locations for CUTM
INSERT INTO locations (id, name, category, building_id, floor, description, latitude, longitude, image_url, is_accessible, is_delivery, tags, opening_hours, created_at) VALUES 
('MAIN_GATE', 'Main Gate', 'entrance', null, 0, 'Main Gate at CUTM', 18.777, 84.093, null, true, true, 'main,gate', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ADMIN_BLOCK', 'Admin Block', 'building', null, 0, 'Admin Block at CUTM', 18.7778, 84.0935, null, true, true, 'admin,block', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ARYABHATTA_GF', 'Aryabhatta Block', 'building', null, 0, 'Aryabhatta Block at CUTM', 18.7785, 84.094, null, true, true, 'aryabhatta,block', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('AGRI_GF', 'School of Agriculture', 'building', null, 0, 'School of Agriculture at CUTM', 18.7795, 84.095, null, true, true, 'school,of,agriculture', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('FISHERIES', 'School of Fisheries', 'building', null, 0, 'School of Fisheries at CUTM', 18.78, 84.0945, null, true, true, 'school,of,fisheries', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('PHARMACY', 'School of Pharmacy', 'building', null, 0, 'School of Pharmacy at CUTM', 18.779, 84.0955, null, true, true, 'school,of,pharmacy', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MANAGEMENT', 'School of Management', 'building', null, 0, 'School of Management at CUTM', 18.7782, 84.0945, null, true, true, 'school,of,management', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('NURSING', 'School of Nursing', 'building', null, 0, 'School of Nursing at CUTM', 18.7788, 84.096, null, true, true, 'school,of,nursing', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('CS_LAB', 'Computer Science Lab', 'classroom/lab', null, 0, 'Computer Science Lab at CUTM', 18.7786, 84.0942, null, true, true, 'computer,science,lab', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('LIBRARY_GF', 'Central Library', 'building', null, 0, 'Central Library at CUTM', 18.778, 84.094, null, true, true, 'central,library', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MAHANADI_HOSTEL', 'Mahanadi Boys Hostel', 'hostel', null, 0, 'Mahanadi Boys Hostel at CUTM', 18.7775, 84.092, null, true, true, 'mahanadi,boys,hostel', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('NAGAVALI_HOSTEL', 'Nagavali Girls Hostel', 'hostel', null, 0, 'Nagavali Girls Hostel at CUTM', 18.779, 84.092, null, true, true, 'nagavali,girls,hostel', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MAHENDRA_HOSTEL', 'Mahendra Tanaya Hostel', 'hostel', null, 0, 'Mahendra Tanaya Hostel at CUTM', 18.7772, 84.0915, null, true, true, 'mahendra,tanaya,hostel', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INDRAVATI_HOSTEL', 'Indravati Hostel', 'hostel', null, 0, 'Indravati Hostel at CUTM', 18.7792, 84.0915, null, true, true, 'indravati,hostel', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('CENTRAL_MESS', 'Central Mess', 'canteen', null, 0, 'Central Mess at CUTM', 18.7777, 84.0925, null, true, true, 'central,mess', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('FOOD_COURT', 'Food Court', 'canteen', null, 0, 'Food Court at CUTM', 18.7775, 84.0928, null, true, true, 'food,court', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('AUDITORIUM', 'Auditorium', 'building', null, 0, 'Auditorium at CUTM', 18.7783, 84.0948, null, true, true, 'auditorium', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('TEMPLE', 'Campus Temple', 'building', null, 0, 'Campus Temple at CUTM', 18.778, 84.0932, null, true, true, 'campus,temple', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('SPORTS_COMPLEX', 'Sports Complex', 'building', null, 0, 'Sports Complex at CUTM', 18.7798, 84.0925, null, true, true, 'sports,complex', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MEDICAL', 'Diagnostics Center', 'building', null, 0, 'Diagnostics Center at CUTM', 18.7776, 84.0942, null, true, true, 'diagnostics,center', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('WELLNESS', 'Ayurveda Wellness Centre', 'building', null, 0, 'Ayurveda Wellness Centre at CUTM', 18.7774, 84.0944, null, true, true, 'ayurveda,wellness,centre', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('GUEST_HOUSE', 'Guest House', 'building', null, 0, 'Guest House at CUTM', 18.777, 84.0938, null, true, true, 'guest,house', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ATM', 'ATM / Bank', 'building', null, 0, 'ATM / Bank at CUTM', 18.7773, 84.0933, null, true, true, 'atm,/,bank', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('PARKING_AREA', 'Parking Area', 'parking', null, 0, 'Parking Area at CUTM', 18.7772, 84.0932, null, true, true, 'parking,area', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MARKET', 'Market Complex', 'building', null, 0, 'Market Complex at CUTM', 18.7771, 84.0928, null, true, true, 'market,complex', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('STAFF_QUARTERS', 'Staff Quarters', 'building', null, 0, 'Staff Quarters at CUTM', 18.7768, 84.092, null, true, true, 'staff,quarters', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('PRODUCTION_LAB', 'Production Labs', 'classroom/lab', null, 0, 'Production Labs at CUTM', 18.7793, 84.0948, null, true, true, 'production,labs', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('APPLIED_SCIENCES', 'School of Applied Sciences', 'building', null, 0, 'School of Applied Sciences at CUTM', 18.7787, 84.095, null, true, true, 'school,of,applied,sciences', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('VOCATIONAL_ED', 'School of Vocational Education', 'building', null, 0, 'School of Vocational Education at CUTM', 18.7795, 84.0955, null, true, true, 'school,of,vocational,education', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('CENTRAL_GARDEN', 'Central Garden', 'garden', null, 0, 'Central Garden at CUTM', 18.7785, 84.0935, null, true, true, 'central,garden', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ARYABHATTA_1F', 'Aryabhatta Block 1F', 'indoor', null, 1, 'Aryabhatta Block 1F at CUTM', 18.7785, 84.094, null, true, true, 'aryabhatta,block,1f', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ARYABHATTA_2F', 'Aryabhatta Block 2F', 'indoor', null, 2, 'Aryabhatta Block 2F at CUTM', 18.7785, 84.094, null, true, true, 'aryabhatta,block,2f', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ARYABHATTA_1F_CLASS', 'Aryabhatta Class 101', 'classroom/lab', null, 1, 'Aryabhatta Class 101 at CUTM', 18.7785, 84.0941, null, true, true, 'aryabhatta,class,101', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ARYABHATTA_2F_LAB', 'Aryabhatta CS Lab', 'classroom/lab', null, 2, 'Aryabhatta CS Lab at CUTM', 18.7785, 84.0941, null, true, true, 'aryabhatta,cs,lab', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('AGRI_1F', 'Agriculture 1F', 'indoor', null, 1, 'Agriculture 1F at CUTM', 18.7795, 84.095, null, true, true, 'agriculture,1f', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('AGRI_1F_LAB', 'Agri Lab 101', 'classroom/lab', null, 1, 'Agri Lab 101 at CUTM', 18.7795, 84.0951, null, true, true, 'agri,lab,101', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('LIBRARY_READING', 'Reading Room', 'indoor', null, 0, 'Reading Room at CUTM', 18.778, 84.0941, null, true, true, 'reading,room', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('ADMIN_REGISTRAR', 'Registrar Office', 'indoor', null, 0, 'Registrar Office at CUTM', 18.7778, 84.0936, null, true, true, 'registrar,office', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('MANAGEMENT_CLASS', 'MBA Classroom', 'classroom/lab', null, 0, 'MBA Classroom at CUTM', 18.7782, 84.0946, null, true, true, 'mba,classroom', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_1', 'Gate Intersection', 'indoor', null, 0, 'Gate Intersection at CUTM', 18.7772, 84.093, null, true, true, 'gate,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_2', 'Food Court Intersection', 'indoor', null, 0, 'Food Court Intersection at CUTM', 18.7775, 84.093, null, true, true, 'food,court,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_3', 'Mess Intersection', 'indoor', null, 0, 'Mess Intersection at CUTM', 18.7778, 84.093, null, true, true, 'mess,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_4', 'Temple Intersection', 'indoor', null, 0, 'Temple Intersection at CUTM', 18.778, 84.093, null, true, true, 'temple,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_5', 'Garden Intersection', 'indoor', null, 0, 'Garden Intersection at CUTM', 18.7785, 84.093, null, true, true, 'garden,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_6', 'North Hostels Intersection', 'indoor', null, 0, 'North Hostels Intersection at CUTM', 18.779, 84.093, null, true, true, 'north,hostels,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_7', 'South West Intersection', 'indoor', null, 0, 'South West Intersection at CUTM', 18.7772, 84.092, null, true, true, 'south,west,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_8', 'Mahanadi Intersection', 'indoor', null, 0, 'Mahanadi Intersection at CUTM', 18.7775, 84.0925, null, true, true, 'mahanadi,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_9', 'Indravati Intersection', 'indoor', null, 0, 'Indravati Intersection at CUTM', 18.7792, 84.092, null, true, true, 'indravati,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_10', 'Sports Intersection', 'indoor', null, 0, 'Sports Intersection at CUTM', 18.7798, 84.093, null, true, true, 'sports,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_11', 'Medical Intersection', 'indoor', null, 0, 'Medical Intersection at CUTM', 18.7774, 84.094, null, true, true, 'medical,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_12', 'Library Intersection', 'indoor', null, 0, 'Library Intersection at CUTM', 18.7778, 84.0938, null, true, true, 'library,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_13', 'Aryabhatta Intersection', 'indoor', null, 0, 'Aryabhatta Intersection at CUTM', 18.7785, 84.0943, null, true, true, 'aryabhatta,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_14', 'Auditorium Intersection', 'indoor', null, 0, 'Auditorium Intersection at CUTM', 18.7782, 84.0948, null, true, true, 'auditorium,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_15', 'Applied Sci Intersection', 'indoor', null, 0, 'Applied Sci Intersection at CUTM', 18.7787, 84.0952, null, true, true, 'applied,sci,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_16', 'Agri Intersection', 'indoor', null, 0, 'Agri Intersection at CUTM', 18.7795, 84.0948, null, true, true, 'agri,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP),
('INT_17', 'Staff Qtrs Intersection', 'indoor', null, 0, 'Staff Qtrs Intersection at CUTM', 18.7768, 84.0925, null, true, true, 'staff,qtrs,intersection', '8:00 AM - 8:00 PM', CURRENT_TIMESTAMP);

-- Insert alerts (disabled by default)
INSERT INTO alerts (id, title, message, type, location_id, is_active, created_at) VALUES 
('ALERT_1', 'Main Gate Construction', 'Construction work at the main gate.', 'warning', 'MAIN_GATE', false, CURRENT_TIMESTAMP),
('ALERT_2', 'Aryabhatta Elevator Maintenance', 'The elevator is closed for maintenance.', 'closure', 'ARYABHATTA_GF', false, CURRENT_TIMESTAMP),
('ALERT_3', 'Extended Library Hours', 'The central library will remain open until midnight.', 'info', 'LIBRARY_GF', false, CURRENT_TIMESTAMP);
